name: Documentation
on: [push, pull_request]

jobs:
  Build_Doc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt --assume-yes install libusb-1.0-0-dev doxygen graphviz texlive
          python3 -m pip install -r ./inference-engine/ie_bridges/python/requirements.txt
          python3 -m pip install lxml

      - name: CMake
        run: |
          mkdir build
          cd build
          cmake -DENABLE_DOCS=ON ..

      - name: Build doc
        run: cmake --build . --target openvino_docs
        working-directory: build
